# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/train_config_sd0/best_whisper.pth'
  config: 'config/train_config.yaml'
data:
  whisper:
    model_name: "base"           # Whisper model size
    lang: "en"                  # language
    audio_max_length: 480000    
  name: "wtimit"
  batch_size: 16
  bucketing: true
  train: data/train
  valid: data/dev
  test: data/test
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.07
  lm_path: 'ckpt/lm_example_sd0/best_ppx.pth'
  lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0.0
  ctc_weight: 0.0
