# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/train_config_sd0/best_whisper.pth'
  config: 'config/train_config.yaml'
data:
  whisper:
    model_name: "large"          # align with teammate strategy
    local_model_path: "ckpt/whisper/large-v3.pt"  # offline checkpoint path
    use_lora: true               # use same LoRA structure for checkpoint loading
    lora_rank: 2
    lora_alpha: 2
    lang: "en"                  # language
    audio_max_length: 480000    
  name: "wtimit"
  batch_size: 2
  bucketing: true
  train: data/train
  valid: data/dev
  test: data/test
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.07
  lm_path: 'ckpt/lm_example_sd0/best_ppx.pth'
  lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0.0
  ctc_weight: 0.0
