data:
  whisper:
    model_name: "large"          # align with teammate strategy
    local_model_path: "ckpt/whisper/large-v3.pt"  # offline checkpoint path
    use_lora: true               # enable LoRA fine-tuning
    lora_rank: 2
    lora_alpha: 2
    lang: "en"                  # language
    audio_max_length: 480000   

  name: "wtimit"
  batch_size: 2
  bucketing: true
  train: data/train
  valid: data/dev
    

hparas:
  valid_step: 1000
  max_step: 50000
  optimizer: 'Adadelta'
  lr: 0.0005
  lr_scheduler: 'fixed'  
  eps: 0.00000001  
