data:
  corpus:
    name: 'aishell'
    path: 'data'
    train_split: ['train']
    dev_split: ['dev']
    bucketing: True
    batch_size: 16
  audio:
    feat_type: 'fbank'
    feat_dim: 40
    frame_length: 25
    frame_shift: 10
    dither: 0
    apply_cmvn: True
    delta_order: 2
    delta_window_size: 2
  text:
    mode: 'character'
    vocab_file: 'data/dict/lang_char.txt'

hparas:
  valid_step: 5000
  max_step: 200001
  tf_start: 1.0
  tf_end: 1.0
  tf_step: 500000
  optimizer: 'Adadelta'
  lr: 1.0
  eps: 0.00000001
  lr_scheduler: 'fixed'
  curriculum: 0

model:
  ctc_weight: 0.5
  encoder:
    prenet: 'vgg'
    module: 'LSTM'
    bidirection: True
    dim: [512, 512, 512, 512, 512]
    dropout: [0, 0, 0, 0, 0]
    layer_norm: [False, False, False, False, False]
    proj: [True, True, True, True, True]
    sample_rate: [1, 1, 1, 1, 1]
    sample_style: 'drop'
  attention:
    mode: 'loc'
    dim: 300
    num_head: 1
    v_proj: False
    temperature: 0.5
    loc_kernel_size: 100
    loc_kernel_num: 10
  decoder:
    module: 'LSTM'
    dim: 512
    layer: 1
    dropout: 0
